DROP SEQUENCE SEQ_MYTEST_NO;
CREATE SEQUENCE SEQ_MYTEST_NO
	START WITH 102
	INCREMENT BY 1
	MAXVALUE 9999
	NOCYCLE
	NOCACHE;

DROP TABLE MYTEST PURGE;
CREATE TABLE MYTEST(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(100),
	NICKNAME VARCHAR2(200)
);
SELECT * FROM MYTEST;
INSERT INTO MYTEST VALUES(100, '조현준', '쟌쥰');
INSERT INTO MYTEST VALUES(101, '이순신', '불멸의이순신');

